"use client"

import { useState } from "react"
import Image from "next/image"
import DataTable from "./DataTable"
import VideoCarousel from "./VideoCarousel"

// Update the seasons array to include 2015/16
const seasons = ["2024/25", "2023/24", "2022/23", "2021/22", "2020/21", "2019/20", "2017/18", "2016/17", "2015/16"]

// Static data for past seasons
const pastSeasonsData = {
  "2023/24": {
    standings: [
      {
        team: "Newcastle",
        logo: "/imgs/fifa/new.png",
        games: 28,
        wins: 25,
        draws: 1,
        losses: 2,
        goalsScored: 110,
        goalsConceded: 41,
        goalDifference: 69,
        points: 76,
        color: "#ea7878", // Red
      },
      {
        team: "Marseille",
        logo: "/imgs/fifa/mar.png",
        games: 28,
        wins: 25,
        draws: 0,
        losses: 3,
        goalsScored: 101,
        goalsConceded: 40,
        goalDifference: 61,
        points: 75,
        color: "#ea7878", // Blue
      },
      {
        team: "Barcelona",
        logo: "/imgs/fifa/bar.png",
        games: 28,
        wins: 23,
        draws: 4,
        losses: 1,
        goalsScored: 120,
        goalsConceded: 30,
        goalDifference: 90,
        points: 73,
        color: "#ea7878", // Purple
      },
      {
        team: "Manchester City",
        logo: "/imgs/fifa/mci.png",
        games: 28,
        wins: 21,
        draws: 6,
        losses: 1,
        goalsScored: 100,
        goalsConceded: 38,
        goalDifference: 62,
        points: 69,
        color: "#ea7878", // Dark Blue
      },
      {
        team: "Real Sosiedad",
        logo: "/imgs/fifa/rs.png",
        games: 28,
        wins: 22,
        draws: 3,
        losses: 3,
        goalsScored: 98,
        goalsConceded: 40,
        goalDifference: 58,
        points: 69,
        color: "#ea7878", // Yellow
      },
      {
        team: "SL Benfica",
        logo: "/imgs/fifa/ben.png",
        games: 28,
        wins: 21,
        draws: 3,
        losses: 4,
        goalsScored: 107,
        goalsConceded: 59,
        goalDifference: 48,
        points: 66,
        color: "#ea7878", // Orange
      },
      {
        team: "Fiorentina",
        logo: "/imgs/fifa/fio.png",
        games: 28,
        wins: 20,
        draws: 6,
        losses: 2,
        goalsScored: 95,
        goalsConceded: 50,
        goalDifference: 45,
        points: 66,
        color: "#ea7878", // Purple
      },
      {
        team: "Bayer Leverkusen",
        logo: "/imgs/fifa/lev.png",
        games: 28,
        wins: 20,
        draws: 3,
        losses: 5,
        goalsScored: 107,
        goalsConceded: 64,
        goalDifference: 43,
        points: 63,
        color: "#ea7878", // Dark Red
      },
      {
        team: "Atletico Madrid",
        logo: "/imgs/fifa/atm.png",
        games: 28,
        wins: 20,
        draws: 2,
        losses: 6,
        goalsScored: 95,
        goalsConceded: 43,
        goalDifference: 52,
        points: 62,
        color: "#ea7878", // Dark Orange
      },
      {
        team: "Real Madrid",
        logo: "/imgs/fifa/rm.png",
        games: 28,
        wins: 19,
        draws: 5,
        losses: 4,
        goalsScored: 104,
        goalsConceded: 57,
        goalDifference: 47,
        points: 62,
        color: "#4b98de", // Navy Blue
      },
      {
        team: "RB Leipzig",
        logo: "/imgs/fifa/rbl.png",
        games: 28,
        wins: 19,
        draws: 4,
        losses: 5,
        goalsScored: 97,
        goalsConceded: 47,
        goalDifference: 50,
        points: 61,
        color: "#ea7878", // Green
      },
      {
        team: "Liverpool",
        logo: "/imgs/fifa/liv.png",
        games: 28,
        wins: 17,
        draws: 7,
        losses: 4,
        goalsScored: 82,
        goalsConceded: 45,
        goalDifference: 37,
        points: 58,
        color: "#ea7878", // Dark Red
      },
      {
        team: "Feyenord",
        logo: "/imgs/fifa/fey.png",
        games: 28,
        wins: 16,
        draws: 4,
        losses: 8,
        goalsScored: 84,
        goalsConceded: 66,
        goalDifference: 18,
        points: 52,
        color: "#ea7878", // Teal
      },
      {
        team: "AS Monaco",
        logo: "/imgs/fifa/mon.png",
        games: 28,
        wins: 15,
        draws: 2,
        losses: 11,
        goalsScored: 89,
        goalsConceded: 72,
        goalDifference: 17,
        points: 47,
        color: "#ea7878", // Orange
      },
      {
        team: "Bayern Munich",
        logo: "/imgs/fifa/bay.png",
        games: 25,
        wins: 14,
        draws: 3,
        losses: 8,
        goalsScored: 84,
        goalsConceded: 49,
        goalDifference: 35,
        points: 45,
        color: "#4b98de", // Red
      },
      {
        team: "Boca Juniors",
        logo: "/imgs/fifa/bj.png",
        games: 28,
        wins: 10,
        draws: 10,
        losses: 8,
        goalsScored: 63,
        goalsConceded: 57,
        goalDifference: 6,
        points: 40,
        color: "#ea7878", // Blue
      },
      {
        team: "Inter",
        logo: "/imgs/fifa/int.png",
        games: 24,
        wins: 12,
        draws: 4,
        losses: 8,
        goalsScored: 69,
        goalsConceded: 62,
        goalDifference: 7,
        points: 40,
        color: "#4b98de", // Dark Blue
      },
      {
        team: "AS Roma",
        logo: "/imgs/fifa/rom.png",
        games: 25,
        wins: 12,
        draws: 3,
        losses: 10,
        goalsScored: 83,
        goalsConceded: 64,
        goalDifference: 19,
        points: 39,
        color: "#4b98de", // Dark Orange
      },
      {
        team: "Napoli",
        logo: "/imgs/fifa/nap.png",
        games: 25,
        wins: 11,
        draws: 5,
        losses: 9,
        goalsScored: 82,
        goalsConceded: 73,
        goalDifference: 9,
        points: 38,
        color: "#4b98de", // Blue
      },
      {
        team: "Brentford",
        logo: "/imgs/fifa/bre.png",
        games: 25,
        wins: 11,
        draws: 3,
        losses: 11,
        goalsScored: 59,
        goalsConceded: 72,
        goalDifference: -13,
        points: 36,
        color: "#4b98de", // Red
      },
      {
        team: "Chelsea",
        logo: "/imgs/fifa/che.png",
        games: 25,
        wins: 11,
        draws: 2,
        losses: 12,
        goalsScored: 68,
        goalsConceded: 68,
        goalDifference: 0,
        points: 35,
        color: "#4b98de", // Blue
      },
      {
        team: "Al Nassr",
        logo: "/imgs/fifa/aln.png",
        games: 25,
        wins: 10,
        draws: 4,
        losses: 11,
        goalsScored: 87,
        goalsConceded: 78,
        goalDifference: 9,
        points: 34,
        color: "#4b98de", // Orange
      },
      {
        team: "SS Lazio",
        logo: "/imgs/fifa/laz.png",
        games: 23,
        wins: 9,
        draws: 7,
        losses: 7,
        goalsScored: 62,
        goalsConceded: 55,
        goalDifference: 7,
        points: 34,
        color: "#4b98de", // Blue
      },
      {
        team: "Athletic Bilbao",
        logo: "/imgs/fifa/atb.png",
        games: 25,
        wins: 8,
        draws: 3,
        losses: 14,
        goalsScored: 60,
        goalsConceded: 78,
        goalDifference: -18,
        points: 27,
        color: "#4b98de", // Red
      },
      {
        team: "River PLate",
        logo: "/imgs/fifa/rp.png",
        games: 26,
        wins: 8,
        draws: 3,
        losses: 15,
        goalsScored: 62,
        goalsConceded: 83,
        goalDifference: -21,
        points: 27,
        color: "#4b98de", // Red
      },
      {
        team: "Juventus",
        logo: "/imgs/fifa/juv.png",
        games: 25,
        wins: 7,
        draws: 5,
        losses: 13,
        goalsScored: 48,
        goalsConceded: 74,
        goalDifference: -26,
        points: 26,
        color: "#4fcb90", // Navy Blue
      },
      {
        team: "Brighton",
        logo: "/imgs/fifa/bri.png",
        games: 26,
        wins: 7,
        draws: 4,
        losses: 15,
        goalsScored: 56,
        goalsConceded: 87,
        goalDifference: -31,
        points: 25,
        color: "#4b98de", // Blue
      },
      {
        team: "Milan",
        logo: "/imgs/fifa/mil.png",
        games: 27,
        wins: 6,
        draws: 6,
        losses: 15,
        goalsScored: 58,
        goalsConceded: 101,
        goalDifference: -43,
        points: 24,
        color: "#4fcb90", // Red
      },
      {
        team: "Porto",
        logo: "/imgs/fifa/por.png",
        games: 26,
        wins: 6,
        draws: 4,
        losses: 16,
        goalsScored: 60,
        goalsConceded: 81,
        goalDifference: -21,
        points: 22,
        color: "#4b98de", // Blue
      },
      {
        team: "PSG",
        logo: "/imgs/fifa/psg.png",
        games: 27,
        wins: 6,
        draws: 4,
        losses: 17,
        goalsScored: 70,
        goalsConceded: 96,
        goalDifference: -26,
        points: 22,
        color: "#4fcb90", // Blue
      },
      {
        team: "Aston Villa",
        logo: "/imgs/fifa/ast.png",
        games: 24,
        wins: 5,
        draws: 4,
        losses: 15,
        goalsScored: 49,
        goalsConceded: 82,
        goalDifference: -33,
        points: 19,
        color: "#4fcb90", // Purple
      },
      {
        team: "Tottenham",
        logo: "/imgs/fifa/tot.png",
        games: 25,
        wins: 5,
        draws: 2,
        losses: 18,
        goalsScored: 48,
        goalsConceded: 95,
        goalDifference: -47,
        points: 17,
        color: "#4fcb90", // Navy Blue
      },
      {
        team: "Al Ahli",
        logo: "/imgs/fifa/ala.png",
        games: 25,
        wins: 5,
        draws: 2,
        losses: 18,
        goalsScored: 29,
        goalsConceded: 81,
        goalDifference: -52,
        points: 17,
        color: "#4fcb90", // Green
      },
      {
        team: "Borussia Dortmund",
        logo: "/imgs/fifa/bor.png",
        games: 23,
        wins: 3,
        draws: 7,
        losses: 13,
        goalsScored: 52,
        goalsConceded: 88,
        goalDifference: -36,
        points: 16,
        color: "#4fcb90", // Yellow
      },
      {
        team: "West Ham",
        logo: "/imgs/fifa/wh.png",
        games: 24,
        wins: 3,
        draws: 6,
        losses: 15,
        goalsScored: 56,
        goalsConceded: 83,
        goalDifference: -27,
        points: 15,
        color: "#4b98de", // Purple
      },
      {
        team: "Arsenal",
        logo: "/imgs/fifa/ars.png",
        games: 27,
        wins: 3,
        draws: 4,
        losses: 20,
        goalsScored: 60,
        goalsConceded: 105,
        goalDifference: -45,
        points: 13,
        color: "#4fcb90", // Red
      },
      {
        team: "Manchester United",
        logo: "/imgs/fifa/mu.png",
        games: 26,
        wins: 2,
        draws: 7,
        losses: 17,
        goalsScored: 43,
        goalsConceded: 88,
        goalDifference: -45,
        points: 13,
        color: "#4fcb90", // Dark Red
      },
      {
        team: "Al Hilal",
        logo: "/imgs/fifa/alh.png",
        games: 25,
        wins: 3,
        draws: 1,
        losses: 21,
        goalsScored: 30,
        goalsConceded: 92,
        goalDifference: -62,
        points: 10,
        color: "#4fcb90", // Blue
      },
      {
        team: "Real Betis",
        logo: "/imgs/fifa/rb.png",
        games: 26,
        wins: 3,
        draws: 1,
        losses: 22,
        goalsScored: 41,
        goalsConceded: 107,
        goalDifference: -66,
        points: 10,
        color: "#4fcb90", // Green
      },
      {
        team: "Galatasaray",
        logo: "/imgs/fifa/gal.png",
        games: 24,
        wins: 2,
        draws: 3,
        losses: 19,
        goalsScored: 31,
        goalsConceded: 90,
        goalDifference: -59,
        points: 9,
        color: "#4fcb90", // Orange
      },
      {
        team: "Atalanta",
        logo: "/imgs/fifa/ata.png",
        games: 24,
        wins: 2,
        draws: 1,
        losses: 21,
        goalsScored: 32,
        goalsConceded: 96,
        goalDifference: -64,
        points: 7,
        color: "#4fcb90", // Blue
      },
      {
        team: "Sevilla",
        logo: "/imgs/fifa/sev.png",
        games: 24,
        wins: 0,
        draws: 4,
        losses: 20,
        goalsScored: 30,
        goalsConceded: 84,
        goalDifference: -54,
        points: 4,
        color: "#4fcb90", // Red
      },
    ],
  },
  "2022/23": {
    standings: [
      {
        team: "Bayern Munich",
        logo: "/imgs/fifa/bay.png",
        games: 44,
        wins: 34,
        draws: 3,
        losses: 7,
        goalsScored: 164,
        goalsConceded: 57,
        goalDifference: 107,
        points: 105,
        color: "#4b98de", // Red
      },
      {
        team: "Liverpool",
        logo: "/imgs/fifa/liv.png",
        games: 44,
        wins: 31,
        draws: 7,
        losses: 6,
        goalsScored: 129,
        goalsConceded: 60,
        goalDifference: 69,
        points: 100,
        color: "#ea7878", // Dark Red
      },
      {
        team: "Bayer Leverkusen",
        logo: "/imgs/fifa/lev.png",
        games: 44,
        wins: 31,
        draws: 7,
        losses: 6,
        goalsScored: 129,
        goalsConceded: 66,
        goalDifference: 63,
        points: 100,
        color: "#ea7878", // Red
      },
      {
        team: "Inter",
        logo: "/imgs/fifa/int.png",
        games: 44,
        wins: 30,
        draws: 8,
        losses: 6,
        goalsScored: 133,
        goalsConceded: 70,
        goalDifference: 63,
        points: 98,
        color: "#ea7878", // Blue
      },
      {
        team: "AFC Richmond",
        logo: "/imgs/fifa/ric.png",
        games: 44,
        wins: 31,
        draws: 5,
        losses: 8,
        goalsScored: 127,
        goalsConceded: 81,
        goalDifference: 46,
        points: 98,
        color: "#ea7878", // Yellow
      },
      {
        team: "Atletico Madrid",
        logo: "/imgs/fifa/atm.png",
        games: 44,
        wins: 30,
        draws: 7,
        losses: 7,
        goalsScored: 134,
        goalsConceded: 77,
        goalDifference: 57,
        points: 97,
        color: "#ea7878", // Red
      },
      {
        team: "Chelsea",
        logo: "/imgs/fifa/che.png",
        games: 44,
        wins: 30,
        draws: 4,
        losses: 10,
        goalsScored: 129,
        goalsConceded: 77,
        goalDifference: 52,
        points: 94,
        color: "#4b98de", // Blue
      },
      {
        team: "Arsenal",
        logo: "/imgs/fifa/ars.png",
        games: 44,
        wins: 29,
        draws: 7,
        losses: 8,
        goalsScored: 116,
        goalsConceded: 68,
        goalDifference: 48,
        points: 94,
        color: "#ea7878", // Red
      },
      {
        team: "Manchester City",
        logo: "/imgs/fifa/mci.png",
        games: 44,
        wins: 28,
        draws: 8,
        losses: 8,
        goalsScored: 131,
        goalsConceded: 67,
        goalDifference: 64,
        points: 92,
        color: "#4b98de", // Blue
      },
      {
        team: "A.S. Roma",
        logo: "/imgs/fifa/rom.png",
        games: 44,
        wins: 26,
        draws: 8,
        losses: 10,
        goalsScored: 111,
        goalsConceded: 86,
        goalDifference: 25,
        points: 86,
        color: "#ea7878", // Dark Orange
      },
      {
        team: "Tottenham",
        logo: "/imgs/fifa/tot.png",
        games: 44,
        wins: 24,
        draws: 8,
        losses: 12,
        goalsScored: 130,
        goalsConceded: 91,
        goalDifference: 39,
        points: 80,
        color: "#4b98de", // Navy Blue
      },
      {
        team: "Eintracht Frankfurt",
        logo: "/imgs/fifa/fra.png",
        games: 44,
        wins: 24,
        draws: 7,
        losses: 13,
        goalsScored: 123,
        goalsConceded: 98,
        goalDifference: 25,
        points: 79,
        color: "#ea7878", // Red
      },
      {
        team: "RB Leipzig",
        logo: "/imgs/fifa/rbl.png",
        games: 44,
        wins: 22,
        draws: 10,
        losses: 12,
        goalsScored: 136,
        goalsConceded: 104,
        goalDifference: 32,
        points: 76,
        color: "#4b98de", // Green
      },
      {
        team: "Manchester United",
        logo: "/imgs/fifa/mu.png",
        games: 44,
        wins: 23,
        draws: 5,
        losses: 16,
        goalsScored: 116,
        goalsConceded: 94,
        goalDifference: 22,
        points: 74,
        color: "#4b98de", // Dark Red
      },
      {
        team: "Newcastle",
        logo: "/imgs/fifa/new.png",
        games: 44,
        wins: 19,
        draws: 5,
        losses: 20,
        goalsScored: 95,
        goalsConceded: 90,
        goalDifference: 5,
        points: 62,
        color: "#4b98de", // Red
      },
      {
        team: "PSV",
        logo: "/imgs/fifa/psv.png",
        games: 44,
        wins: 15,
        draws: 10,
        losses: 19,
        goalsScored: 126,
        goalsConceded: 115,
        goalDifference: 11,
        points: 55,
        color: "#4b98de", // Red
      },
      {
        team: "Porto",
        logo: "/imgs/fifa/por.png",
        games: 28,
        wins: 15,
        draws: 8,
        losses: 5,
        goalsScored: 75,
        goalsConceded: 53,
        goalDifference: 22,
        points: 53,
        color: "#ea7878", // Blue
      },
      {
        team: "Villarreal",
        logo: "/imgs/fifa/vil.png",
        games: 28,
        wins: 16,
        draws: 4,
        losses: 8,
        goalsScored: 85,
        goalsConceded: 63,
        goalDifference: 22,
        points: 52,
        color: "#ea7878", // Yellow
      },
      {
        team: "Atalanta",
        logo: "/imgs/fifa/ata.png",
        games: 28,
        wins: 16,
        draws: 2,
        losses: 10,
        goalsScored: 85,
        goalsConceded: 65,
        goalDifference: 20,
        points: 50,
        color: "#ea7878", // Blue
      },
      {
        team: "Dinamo Zagreb",
        logo: "/imgs/fifa/zag.png",
        games: 28,
        wins: 15,
        draws: 3,
        losses: 10,
        goalsScored: 79,
        goalsConceded: 58,
        goalDifference: 21,
        points: 48,
        color: "#ea7878", // Blue
      },
      {
        team: "Rangers",
        logo: "/imgs/fifa/ran.png",
        games: 28,
        wins: 14,
        draws: 5,
        losses: 9,
        goalsScored: 70,
        goalsConceded: 63,
        goalDifference: 7,
        points: 47,
        color: "#ea7878", // Blue
      },
      {
        team: "Ajax",
        logo: "/imgs/fifa/aja.png",
        games: 28,
        wins: 13,
        draws: 6,
        losses: 9,
        goalsScored: 64,
        goalsConceded: 49,
        goalDifference: 15,
        points: 45,
        color: "#ea7878", // Red
      },
      {
        team: "Real Madrid",
        logo: "/imgs/fifa/rm.png",
        games: 44,
        wins: 13,
        draws: 4,
        losses: 27,
        goalsScored: 96,
        goalsConceded: 139,
        goalDifference: -43,
        points: 43,
        color: "#4fcb90", // Navy Blue
      },
      {
        team: "PSG",
        logo: "/imgs/fifa/psg.png",
        games: 44,
        wins: 11,
        draws: 9,
        losses: 24,
        goalsScored: 104,
        goalsConceded: 128,
        goalDifference: -24,
        points: 42,
        color: "#4fcb90", // Blue
      },
      {
        team: "West Ham",
        logo: "/imgs/fifa/wh.png",
        games: 28,
        wins: 12,
        draws: 4,
        losses: 12,
        goalsScored: 78,
        goalsConceded: 66,
        goalDifference: 12,
        points: 40,
        color: "#4b98de", // Purple
      },
      {
        team: "AS Monaco",
        logo: "/imgs/fifa/mon.png",
        games: 28,
        wins: 11,
        draws: 6,
        losses: 11,
        goalsScored: 76,
        goalsConceded: 67,
        goalDifference: 9,
        points: 39,
        color: "#4b98de", // Orange
      },
      {
        team: "Sporting CP",
        logo: "/imgs/fifa/spo.png",
        games: 28,
        wins: 12,
        draws: 3,
        losses: 13,
        goalsScored: 65,
        goalsConceded: 59,
        goalDifference: 6,
        points: 39,
        color: "#4b98de", // Green
      },
      {
        team: "Milan",
        logo: "/imgs/fifa/mil.png",
        games: 44,
        wins: 8,
        draws: 11,
        losses: 25,
        goalsScored: 91,
        goalsConceded: 117,
        goalDifference: -26,
        points: 35,
        color: "#4fcb90", // Red
      },
      {
        team: "Lille OSC",
        logo: "/imgs/fifa/lil.png",
        games: 28,
        wins: 10,
        draws: 4,
        losses: 14,
        goalsScored: 61,
        goalsConceded: 78,
        goalDifference: -17,
        points: 34,
        color: "#4b98de", // Blue
      },
      {
        team: "S.L. Benfica",
        logo: "/imgs/fifa/ben.png",
        games: 44,
        wins: 9,
        draws: 7,
        losses: 28,
        goalsScored: 69,
        goalsConceded: 137,
        goalDifference: -68,
        points: 34,
        color: "#4fcb90", // Orange
      },
      {
        team: "Napoli",
        logo: "/imgs/fifa/nap.png",
        games: 44,
        wins: 9,
        draws: 5,
        losses: 30,
        goalsScored: 83,
        goalsConceded: 154,
        goalDifference: -71,
        points: 32,
        color: "#4fcb90", // Blue
      },
      {
        team: "RB Salzburg",
        logo: "/imgs/fifa/rbs.png",
        games: 28,
        wins: 8,
        draws: 5,
        losses: 15,
        goalsScored: 77,
        goalsConceded: 81,
        goalDifference: -4,
        points: 29,
        color: "#4b98de", // Red
      },
      {
        team: "Barcelona",
        logo: "/imgs/fifa/bar.png",
        games: 44,
        wins: 8,
        draws: 5,
        losses: 31,
        goalsScored: 63,
        goalsConceded: 133,
        goalDifference: -70,
        points: 29,
        color: "#4fcb90", // Purple
      },
      {
        team: "Adana Demirspor",
        logo: "/imgs/fifa/ada.png",
        games: 28,
        wins: 6,
        draws: 8,
        losses: 14,
        goalsScored: 68,
        goalsConceded: 86,
        goalDifference: -18,
        points: 26,
        color: "#4b98de", // Blue
      },
      {
        team: "Borussia Dortmund",
        logo: "/imgs/fifa/bor.png",
        games: 44,
        wins: 6,
        draws: 8,
        losses: 30,
        goalsScored: 88,
        goalsConceded: 151,
        goalDifference: -63,
        points: 26,
        color: "#4fcb90", // Yellow
      },
      {
        team: "Juventus",
        logo: "/imgs/fifa/juv.png",
        games: 44,
        wins: 5,
        draws: 9,
        losses: 30,
        goalsScored: 73,
        goalsConceded: 139,
        goalDifference: -66,
        points: 24,
        color: "#4fcb90", // Navy Blue
      },
      {
        team: "Wolverhampton",
        logo: "/imgs/fifa/wol.png",
        games: 28,
        wins: 5,
        draws: 2,
        losses: 21,
        goalsScored: 52,
        goalsConceded: 107,
        goalDifference: -55,
        points: 17,
        color: "#4fcb90", // Orange
      },
      {
        team: "S.S. Lazio",
        logo: "/imgs/fifa/laz.png",
        games: 28,
        wins: 4,
        draws: 1,
        losses: 23,
        goalsScored: 23,
        goalsConceded: 91,
        goalDifference: -68,
        points: 13,
        color: "#4fcb90", // Blue
      },
      {
        team: "Leicester",
        logo: "/imgs/fifa/lei.png",
        games: 28,
        wins: 3,
        draws: 3,
        losses: 22,
        goalsScored: 54,
        goalsConceded: 114,
        goalDifference: -60,
        points: 12,
        color: "#4fcb90", // Blue
      },
      {
        team: "Athletic Bilbao",
        logo: "/imgs/fifa/atb.png",
        games: 28,
        wins: 3,
        draws: 2,
        losses: 23,
        goalsScored: 32,
        goalsConceded: 103,
        goalDifference: -71,
        points: 11,
        color: "#4fcb90", // Red
      },
      {
        team: "Sevilla",
        logo: "/imgs/fifa/sev.png",
        games: 28,
        wins: 1,
        draws: 3,
        losses: 24,
        goalsScored: 29,
        goalsConceded: 95,
        goalDifference: -66,
        points: 6,
        color: "#4fcb90", // Red
      },
      {
        team: "Nottingham Forest",
        logo: "/imgs/fifa/nf.png",
        games: 28,
        wins: 1,
        draws: 2,
        losses: 25,
        goalsScored: 34,
        goalsConceded: 106,
        goalDifference: -72,
        points: 5,
        color: "#4fcb90", // Red
      },
    ],
  },
  "2021/22": {
    description: "Some data was lost. The standings table will be updated as soon as it's restored.",
    standings: [
      {
        team: "Liverpool",
        logo: "/imgs/fifa/liv.png",
        games:27,
        wins: 23,
        draws: 2,
        losses: 2,
        goalsScored: 85,
        goalsConceded: 37,
        goalDifference: 48,
        points: 71,
        color: "#ea7878", // Dark Red
      },
      {
        team: "Tottenham",
        logo: "/imgs/fifa/tot.png",
        games: 27,
        wins: 21,
        draws: 2,
        losses: 4,
        goalsScored: 113,
        goalsConceded: 45,
        goalDifference: 68,
        points: 65,
        color: "#4b98de", // Navy Blue
      },
      {
        team: "Manchester United",
        logo: "/imgs/fifa/mu.png",
        games: 27,
        wins: 16,
        draws: 7,
        losses: 4,
        goalsScored: 94,
        goalsConceded: 70,
        goalDifference: 24,
        points: 55,
        color: "#ea7878", // Dark Red
      },
      {
        team: "Atletico Madrid",
        logo: "/imgs/fifa/atm.png",
        games: 27,
        wins:17,
        draws: 4,
        losses: 6,
        goalsScored: 87,
        goalsConceded: 57,
        goalDifference: 30,
        points: 55,
        color: "#ea7878", // Red
      },
      {
        team: "RB Leipzig",
        logo: "/imgs/fifa/rbl.png",
        games: 15,
        wins: 7,
        draws: 6,
        losses: 2,
        goalsScored: 32,
        goalsConceded: 19,
        goalDifference: 13,
        points: 27,
        color: "#ea7878", // Green
      },
      {
        team: "Sevilla",
        logo: "/imgs/fifa/sev.png",
        games: 15,
        wins: 8,
        draws: 5,
        losses: 2,
        goalsScored: 35,
        goalsConceded: 26,
        goalDifference: 9,
        points: 29,
        color: "#ea7878", // Red
      },
      {
        team: "Everton",
        logo: "/imgs/fifa/eve.png",
        games: 15,
        wins: 8,
        draws: 1,
        losses: 6,
        goalsScored: 37,
        goalsConceded: 35,
        goalDifference: 2,
        points: 25,
        color: "#4b98de", // Blue
      },
      {
        team: "Chelsea",
        logo: "/imgs/fifa/che.png",
        games: 15,
        wins: 7,
        draws: 4,
        losses: 4,
        goalsScored: 44,
        goalsConceded: 33,
        goalDifference: 11,
        points: 25,
        color: "#4b98de", // Blue
      },
      {
        team: "Real Madrid",
        logo: "/imgs/fifa/rm.png",
        games: 15,
        wins: 7,
        draws: 3,
        losses: 5,
        goalsScored: 32,
        goalsConceded: 27,
        goalDifference: 5,
        points: 24,
        color: "#4b98de", // Navy Blue
      },
      {
        team: "Napoli",
        logo: "/imgs/fifa/nap.png",
        games: 15,
        wins: 5,
        draws: 5,
        losses: 5,
        goalsScored: 35,
        goalsConceded: 35,
        goalDifference: 0,
        points: 20,
        color: "#ea7878", // Blue
      },
      {
        team: "AS Monaco",
        logo: "/imgs/fifa/mon.png",
        games: 15,
        wins: 7,
        draws: 3,
        losses: 5,
        goalsScored: 41,
        goalsConceded: 44,
        goalDifference: -3,
        points: 24,
        color: "#4b98de", // Orange
      },
      {
        team: "Inter",
        logo: "/imgs/fifa/int.png",
        games: 15,
        wins: 6,
        draws: 4,
        losses: 5,
        goalsScored: 34,
        goalsConceded: 33,
        goalDifference: 1,
        points: 22,
        color: "#ea7878", // Blue
      },
      {
        team: "Lille",
        logo: "/imgs/fifa/lil.png",
        games: 15,
        wins: 5,
        draws: 4,
        losses: 6,
        goalsScored: 32,
        goalsConceded: 36,
        goalDifference: -4,
        points: 19,
        color: "#4b98de", // Blue
      },
      {
        team: "PSG",
        logo: "/imgs/fifa/psg.png",
        games: 15,
        wins: 7,
        draws: 2,
        losses: 6,
        goalsScored: 39,
        goalsConceded: 44,
        goalDifference: -5,
        points: 23,
        color: "#4fcb90", // Blue
      },
      {
        team: "Barcelona",
        logo: "/imgs/fifa/bar.png",
        games: 15,
        wins: 6,
        draws: 3,
        losses: 6,
        goalsScored: 38,
        goalsConceded: 42,
        goalDifference: -4,
        points: 21,
        color: "#4b98de", // Purple
      },
      {
        team: "Borussia Dortmund",
        logo: "/imgs/fifa/bor.png",
        games: 15,
        wins: 5,
        draws: 3,
        losses: 7,
        goalsScored: 35,
        goalsConceded: 45,
        goalDifference: -10,
        points: 18,
        color: "#4b98de", // Yellow
      },
      {
        team: "Juventus",
        logo: "/imgs/fifa/juv.png",
        games: 15,
        wins: 4,
        draws: 3,
        losses: 8,
        goalsScored: 31,
        goalsConceded: 37,
        goalDifference: -6,
        points: 15,
        color: "#4fcb90", // Navy Blue
      },
      {
        team: "Atalanta",
        logo: "/imgs/fifa/ata.png",
        games: 15,
        wins: 4,
        draws: 3,
        losses: 8,
        goalsScored: 30,
        goalsConceded: 44,
        goalDifference: -14,
        points: 15,
        color: "#ea7878", // Blue
      },
      {
        team: "Bayern Munich",
        logo: "/imgs/fifa/bay.png",
        games: 15,
        wins: 3,
        draws: 3,
        losses: 9,
        goalsScored: 29,
        goalsConceded: 58,
        goalDifference: -29,
        points: 12,
        color: "#4fcb90", // Red
      },
      {
        team: "Arsenal",
        logo: "/imgs/fifa/ars.png",
        games: 15,
        wins: 3,
        draws: 2,
        losses: 10,
        goalsScored: 31,
        goalsConceded: 46,
        goalDifference: -15,
        points: 11,
        color: "#4fcb90", // Red
      },
      {
        team: "Leicester",
        logo: "/imgs/fifa/lei.png",
        games: 15,
        wins: 2,
        draws: 3,
        losses: 10,
        goalsScored: 28,
        goalsConceded: 52,
        goalDifference: -24,
        points: 9,
        color: "#4fcb90", // Blue
      },
      {
        team: "Real Sociedad",
        logo: "/imgs/fifa/rs.png",
        games: 15,
        wins: 2,
        draws: 1,
        losses: 12,
        goalsScored: 27,
        goalsConceded: 50,
        goalDifference: -23,
        points: 7,
        color: "#4fcb90", // Yellow
      },
      {
        team: "AC Milan",
        logo: "/imgs/fifa/mil.png",
        games: 15,
        wins: 1,
        draws: 2,
        losses: 12,
        goalsScored: 25,
        goalsConceded: 48,
        goalDifference: -23,
        points: 5,
        color: "#4fcb90", // Red
      },
      {
        team: "Manchester City",
        logo: "/imgs/fifa/mci.png",
        games: 15,
        wins: 1,
        draws: 1,
        losses: 13,
        goalsScored: 20,
        goalsConceded: 52,
        goalDifference: -32,
        points: 4,
        color: "#4fcb90", // Blue
      },
    ],
  },
  "2020/21": {
    standings: [
      {
        team: "Liverpool",
        logo: "/imgs/fifa/liv.png",
        games: 40,
        wins: 32,
        draws: 6,
        losses: 2,
        goalsScored: 161,
        goalsConceded: 50,
        goalDifference: 111,
        points: 102,
        color: "#ea7878", // Dark Red
      },
      {
        team: "Real Madrid",
        logo: "/imgs/fifa/rm.png",
        games: 40,
        wins: 29,
        draws: 5,
        losses: 6,
        goalsScored: 146,
        goalsConceded: 76,
        goalDifference: 70,
        points: 92,
        color: "#4b98de", // Navy Blue
      },
      {
        team: "RB Leipzig",
        logo: "/imgs/fifa/rbl.png",
        games: 40,
        wins: 28,
        draws: 5,
        losses: 7,
        goalsScored: 138,
        goalsConceded: 77,
        goalDifference: 61,
        points: 89,
        color: "#ea7878", // Green
      },
      {
        team: "Lazio",
        logo: "/imgs/fifa/laz.png",
        games: 40,
        wins: 28,
        draws: 4,
        losses: 8,
        goalsScored: 143,
        goalsConceded: 88,
        goalDifference: 55,
        points: 88,
        color: "#ea7878", // Blue
      },
      {
        team: "Borussia Dortmund",
        logo: "/imgs/fifa/bor.png",
        games: 40,
        wins: 26,
        draws: 9,
        losses: 5,
        goalsScored: 142,
        goalsConceded: 85,
        goalDifference: 57,
        points: 87,
        color: "#ea7878", // Yellow
      },
      {
        team: "Arsenal",
        logo: "/imgs/fifa/ars.png",
        games: 40,
        wins: 26,
        draws: 4,
        losses: 10,
        goalsScored: 146,
        goalsConceded: 87,
        goalDifference: 59,
        points: 82,
        color: "#ea7878", // Red
      },
      {
        team: "Manchester City",
        logo: "/imgs/fifa/mci.png",
        games: 40,
        wins: 25,
        draws: 6,
        losses: 9,
        goalsScored: 145,
        goalsConceded: 88,
        goalDifference: 57,
        points: 81,
        color: "#4b98de", // Blue
      },
      {
        team: "Tottenham",
        logo: "/imgs/fifa/tot.png",
        games: 40,
        wins: 23,
        draws: 8,
        losses: 9,
        goalsScored: 137,
        goalsConceded: 92,
        goalDifference: 45,
        points: 77,
        color: "#ea7878", // Navy Blue
      },
      {
        team: "Sevillia",
        logo: "/imgs/fifa/sev.png",
        games: 40,
        wins: 24,
        draws: 3,
        losses: 13,
        goalsScored: 116,
        goalsConceded: 87,
        goalDifference: 29,
        points: 75,
        color: "#ea7878", // Red
      },
      {
        team: "AC Milan",
        logo: "/imgs/fifa/mil.png",
        games: 40,
        wins: 23,
        draws: 5,
        losses: 12,
        goalsScored: 141,
        goalsConceded: 97,
        goalDifference: 44,
        points: 74,
        color: "#ea7878", // Red
      },
      {
        team: "Chelsea",
        logo: "/imgs/fifa/che.png",
        games: 40,
        wins: 22,
        draws: 7,
        losses: 11,
        goalsScored: 157,
        goalsConceded: 93,
        goalDifference: 64,
        points: 73,
        color: "#4b98de", // Blue
      },
      {
        team: "Olympique Lyon",
        logo: "/imgs/fifa/lyo.png",
        games: 40,
        wins: 23,
        draws: 4,
        losses: 13,
        goalsScored: 128,
        goalsConceded: 92,
        goalDifference: 36,
        points: 73,
        color: "#ea7878", // Blue
      },
      {
        team: "Atalanta",
        logo: "/imgs/fifa/ata.png",
        games: 40,
        wins: 21,
        draws: 10,
        losses: 9,
        goalsScored: 135,
        goalsConceded: 101,
        goalDifference: 34,
        points: 73,
        color: "#ea7878", // Blue
      },
      {
        team: "Atletico Madrid",
        logo: "/imgs/fifa/atm.png",
        games: 40,
        wins: 21,
        draws: 6,
        losses: 13,
        goalsScored: 147,
        goalsConceded: 100,
        goalDifference: 47,
        points: 69,
        color: "#4b98de", // Red
      },
      {
        team: "Everton",
        logo: "/imgs/fifa/eve.png",
        games: 40,
        wins: 18,
        draws: 7,
        losses: 15,
        goalsScored: 131,
        goalsConceded: 120,
        goalDifference: 11,
        points: 61,
        color: "#4b98de", // Blue
      },
      {
        team: "Real Sociedad",
        logo: "/imgs/fifa/rs.png",
        games: 40,
        wins: 16,
        draws: 11,
        losses: 13,
        goalsScored: 138,
        goalsConceded: 122,
        goalDifference: 16,
        points: 59,
        color: "#4b98de", // Yellow
      },
      {
        team: "Manchester United",
        logo: "/imgs/fifa/mu.png",
        games: 40,
        wins: 18,
        draws: 5,
        losses: 17,
        goalsScored: 112,
        goalsConceded: 106,
        goalDifference: 6,
        points: 59,
        color: "#4b98de", // Dark Red
      },
      {
        team: "Wolverhampton",
        logo: "/imgs/fifa/wol.png",
        games: 40,
        wins: 15,
        draws: 7,
        losses: 18,
        goalsScored: 123,
        goalsConceded: 135,
        goalDifference: -12,
        points: 52,
        color: "#4b98de", // Orange
      },
      {
        team: "Napoli",
        logo: "/imgs/fifa/nap.png",
        games: 40,
        wins: 16,
        draws: 3,
        losses: 21,
        goalsScored: 126,
        goalsConceded: 130,
        goalDifference: -4,
        points: 51,
        color: "#4b98de", // Blue
      },
      {
        team: "Juventus",
        logo: "/imgs/fifa/juv.png",
        games: 40,
        wins: 15,
        draws: 3,
        losses: 22,
        goalsScored: 97,
        goalsConceded: 140,
        goalDifference: -43,
        points: 48,
        color: "#4fcb90", // Navy Blue
      },
      {
        team: "Leicester",
        logo: "/imgs/fifa/lei.png",
        games: 40,
        wins: 14,
        draws: 3,
        losses: 23,
        goalsScored: 119,
        goalsConceded: 118,
        goalDifference: 1,
        points: 45,
        color: "#4b98de", // Blue
      },
      {
        team: "Bayern Munich",
        logo: "/imgs/fifa/bay.png",
        games: 40,
        wins: 12,
        draws: 4,
        losses: 24,
        goalsScored: 103,
        goalsConceded: 145,
        goalDifference: -42,
        points: 40,
        color: "#4fcb90", // Red
      },
      {
        team: "Barcelona",
        logo: "/imgs/fifa/bar.png",
        games: 40,
        wins: 8,
        draws: 8,
        losses: 24,
        goalsScored: 106,
        goalsConceded: 155,
        goalDifference: -49,
        points: 32,
        color: "#4fcb90", // Purple
      },
      {
        team: "PSG",
        logo: "/imgs/fifa/psg.png",
        games: 40,
        wins: 9,
        draws: 5,
        losses: 26,
        goalsScored: 106,
        goalsConceded: 182,
        goalDifference: -76,
        points: 32,
        color: "#4fcb90", // Blue
      },
      {
        team: "Atletic Bilbao",
        logo: "/imgs/fifa/atb.png",
        games: 40,
        wins: 5,
        draws: 9,
        losses: 26,
        goalsScored: 76,
        goalsConceded: 145,
        goalDifference: -69,
        points: 24,
        color: "#4fcb90", // Red
      },
      {
        team: "Porto",
        logo: "/imgs/fifa/por.png",
        games: 40,
        wins: 7,
        draws: 3,
        losses: 30,
        goalsScored: 74,
        goalsConceded: 162,
        goalDifference: -88,
        points: 24,
        color: "#4fcb90", // Blue
      },
      {
        team: "Inter",
        logo: "/imgs/fifa/int.png",
        games: 40,
        wins: 6,
        draws: 4,
        losses: 30,
        goalsScored: 80,
        goalsConceded: 179,
        goalDifference: -99,
        points: 22,
        color: "#4fcb90", // Blue
      },
      {
        team: "Benfica",
        logo: "/imgs/fifa/ben.png",
        games: 40,
        wins: 3,
        draws: 5,
        losses: 32,
        goalsScored: 69,
        goalsConceded: 177,
        goalDifference: -108,
        points: 14,
        color: "#4fcb90", // Orange
      },
      {
        team: "Ajax",
        logo: "/imgs/fifa/aja.png",
        games: 40,
        wins: 3,
        draws: 2,
        losses: 35,
        goalsScored: 57,
        goalsConceded: 168,
        goalDifference: -111,
        points: 11,
        color: "#4fcb90", // Red
      },
      {
        team: "Bayer Leverkusen",
        logo: "/imgs/fifa/lev.png",
        games: 40,
        wins: 1,
        draws: 5,
        losses: 34,
        goalsScored: 63,
        goalsConceded: 165,
        goalDifference: -102,
        points: 8,
        color: "#4fcb90", // Red
      },
    ],
  },
  "2019/20": {
    standings: [
      {
        team: "Borussia Dortmund",
        logo: "/imgs/fifa/bor.png",
        games: 32,
        wins: 27,
        draws: 3,
        losses: 2,
        goalsScored: 136,
        goalsConceded: 50,
        goalDifference: 86,
        points: 84,
        color: "#ea7878", // Yellow
      },
      {
        team: "Ajax",
        logo: "/imgs/fifa/aja.png",
        games: 32,
        wins: 24,
        draws: 5,
        losses: 3,
        goalsScored: 122,
        goalsConceded: 56,
        goalDifference: 66,
        points: 77,
        color: "#ea7878", // Red
      },
      {
        team: "Liverpool",
        logo: "/imgs/fifa/liv.png",
        games: 32,
        wins: 24,
        draws: 3,
        losses: 5,
        goalsScored: 132,
        goalsConceded: 46,
        goalDifference: 86,
        points: 75,
        color: "#ea7878", // Dark Red
      },
      {
        team: "Inter",
        logo: "/imgs/fifa/int.png",
        games: 32,
        wins: 22,
        draws: 6,
        losses: 4,
        goalsScored: 126,
        goalsConceded: 69,
        goalDifference: 57,
        points: 72,
        color: "#ea7878", // Blue
      },
      {
        team: "Bayern Munich",
        logo: "/imgs/fifa/bay.png",
        games: 32,
        wins: 21,
        draws: 6,
        losses: 5,
        goalsScored: 108,
        goalsConceded: 58,
        goalDifference: 50,
        points: 69,
        color: "#ea7878", // Red
      },
      {
        team: "PSG",
        logo: "/imgs/fifa/psg.png",
        games: 32,
        wins: 22,
        draws: 3,
        losses: 7,
        goalsScored: 118,
        goalsConceded: 72,
        goalDifference: 46,
        points: 69,
        color: "#ea7878", // Blue
      },
      {
        team: "Napoli",
        logo: "/imgs/fifa/nap.png",
        games: 32,
        wins: 21,
        draws: 5,
        losses: 6,
        goalsScored: 124,
        goalsConceded: 77,
        goalDifference: 47,
        points: 68,
        color: "#ea7878", // Blue
      },
      {
        team: "Olympique Lyon",
        logo: "/imgs/fifa/lyo.png",
        games: 32,
        wins: 20,
        draws: 6,
        losses: 6,
        goalsScored: 112,
        goalsConceded: 69,
        goalDifference: 43,
        points: 66,
        color: "#ea7878", // Blue
      },
      {
        team: "Porto",
        logo: "/imgs/fifa/por.png",
        games: 32,
        wins: 19,
        draws: 5,
        losses: 8,
        goalsScored: 118,
        goalsConceded: 78,
        goalDifference: 40,
        points: 62,
        color: "#4b98de", // Blue
      },
      {
        team: "RB Leipzig",
        logo: "/imgs/fifa/rbl.png",
        games: 32,
        wins: 18,
        draws: 7,
        losses: 7,
        goalsScored: 114,
        goalsConceded: 70,
        goalDifference: 44,
        points: 61,
        color: "#4b98de", // Green
      },
      {
        team: "Tottenham",
        logo: "/imgs/fifa/tot.png",
        games: 32,
        wins: 18,
        draws: 5,
        losses: 9,
        goalsScored: 125,
        goalsConceded: 75,
        goalDifference: 50,
        points: 59,
        color: "#4b98de", // Navy Blue
      },
      {
        team: "Manchester United",
        logo: "/imgs/fifa/mu.png",
        games: 32,
        wins: 19,
        draws: 2,
        losses: 11,
        goalsScored: 111,
        goalsConceded: 75,
        goalDifference: 36,
        points: 59,
        color: "#4b98de", // Dark Red
      },
      {
        team: "Valencia",
        logo: "/imgs/fifa/val.png",
        games: 32,
        wins: 17,
        draws: 5,
        losses: 10,
        goalsScored: 107,
        goalsConceded: 79,
        goalDifference: 28,
        points: 56,
        color: "#4b98de", // Orange
      },
      {
        team: "Monaco",
        logo: "/imgs/fifa/mon.png",
        games: 32,
        wins: 18,
        draws: 1,
        losses: 13,
        goalsScored: 108,
        goalsConceded: 74,
        goalDifference: 34,
        points: 55,
        color: "#4b98de", // Orange
      },
      {
        team: "Chelsea",
        logo: "/imgs/fifa/che.png",
        games: 32,
        wins: 16,
        draws: 4,
        losses: 12,
        goalsScored: 102,
        goalsConceded: 79,
        goalDifference: 23,
        points: 52,
        color: "#4b98de", // Blue
      },
      {
        team: "Leicester City",
        logo: "/imgs/fifa/lei.png",
        games: 32,
        wins: 12,
        draws: 6,
        losses: 14,
        goalsScored: 80,
        goalsConceded: 85,
        goalDifference: -5,
        points: 42,
        color: "#4b98de", // Blue
      },
      {
        team: "Barcelona",
        logo: "/imgs/fifa/bar.png",
        games: 32,
        wins: 7,
        draws: 1,
        losses: 24,
        goalsScored: 55,
        goalsConceded: 125,
        goalDifference: -70,
        points: 22,
        color: "#4fcb90", // Purple
      },
      {
        team: "Juventus",
        logo: "/imgs/fifa/juv.png",
        games: 32,
        wins: 2,
        draws: 6,
        losses: 24,
        goalsScored: 57,
        goalsConceded: 140,
        goalDifference: -83,
        points: 12,
        color: "#4fcb90", // Navy Blue
      },
      {
        team: "Manchester City",
        logo: "/imgs/fifa/mci.png",
        games: 32,
        wins: 2,
        draws: 5,
        losses: 25,
        goalsScored: 56,
        goalsConceded: 144,
        goalDifference: -88,
        points: 11,
        color: "#4fcb90", // Blue
      },
      {
        team: "Atletico Madrid",
        logo: "/imgs/fifa/atm.png",
        games: 32,
        wins: 1,
        draws: 5,
        losses: 26,
        goalsScored: 49,
        goalsConceded: 143,
        goalDifference: -94,
        points: 8,
        color: "#4fcb90", // Red
      },
      {
        team: "Bayer Leverkusen",
        logo: "/imgs/fifa/lev.png",
        games: 32,
        wins: 2,
        draws: 2,
        losses: 28,
        goalsScored: 57,
        goalsConceded: 153,
        goalDifference: -96,
        points: 8,
        color: "#4fcb90", // Red
      },
      {
        team: "Real Madrid",
        logo: "/imgs/fifa/rm.png",
        games: 32,
        wins: 2,
        draws: 2,
        losses: 28,
        goalsScored: 51,
        goalsConceded: 154,
        goalDifference: -103,
        points: 8,
        color: "#4fcb90", // Navy Blue
      },
      {
        team: "Everton",
        logo: "/imgs/fifa/eve.png",
        games: 32,
        wins: 1,
        draws: 2,
        losses: 29,
        goalsScored: 43,
        goalsConceded: 138,
        goalDifference: -95,
        points: 5,
        color: "#4fcb90", // Blue
      },
      {
        team: "Arsenal",
        logo: "/imgs/fifa/ars.png",
        games: 32,
        wins: 1,
        draws: 2,
        losses: 29,
        goalsScored: 44,
        goalsConceded: 146,
        goalDifference: -102,
        points: 5,
        color: "#4fcb90", // Red
      },
    ],
  },
  "2017/18": {
    description: "This season was not completed due to a suspension. No winner was determined.",
    standings: [
      {
        team: "Manchester United",
        logo: "/imgs/fifa/mu.png",
        games: 44,
        wins: 24,
        draws: 8,
        losses: 12,
        goalsScored: 116,
        goalsConceded: 89,
        goalDifference: 27,
        points: 80,
        color: "#4fcb90", // Dark Red
      },
      {
        team: "Bayern Munich",
        logo: "/imgs/fifa/bay.png",
        games: 39,
        wins: 23,
        draws: 8,
        losses: 8,
        goalsScored: 113,
        goalsConceded: 71,
        goalDifference: 42,
        points: 77,
        color: "#ea7878", // Red
      },
      {
        team: "Juventus",
        logo: "/imgs/fifa/juv.png",
        games: 47,
        wins: 22,
        draws: 10,
        losses: 15,
        goalsScored: 110,
        goalsConceded: 92,
        goalDifference: 18,
        points: 76,
        color: "#4fcb90", // Navy Blue
      },
      {
        team: "Real Madrid",
        logo: "/imgs/fifa/rm.png",
        games: 37,
        wins: 23,
        draws: 6,
        losses: 8,
        goalsScored: 115,
        goalsConceded: 80,
        goalDifference: 35,
        points: 75,
        color: "#4b98de", // Navy Blue
      },
      {
        team: "Monaco",
        logo: "/imgs/fifa/mon.png",
        games: 44,
        wins: 23,
        draws: 5,
        losses: 16,
        goalsScored: 107,
        goalsConceded: 89,
        goalDifference: 18,
        points: 74,
        color: "#4b98de", // Orange
      },
      {
        team: "Everton",
        logo: "/imgs/fifa/eve.png",
        games: 45,
        wins: 20,
        draws: 11,
        losses: 14,
        goalsScored: 105,
        goalsConceded: 84,
        goalDifference: 21,
        points: 71,
        color: "#4fcb90", // Blue
      },
      {
        team: "Barcelona",
        logo: "/imgs/fifa/bar.png",
        games: 35,
        wins: 21,
        draws: 7,
        losses: 7,
        goalsScored: 105,
        goalsConceded: 80,
        goalDifference: 25,
        points: 70,
        color: "#4fcb90", // Purple
      },
      {
        team: "Borussia Dortmund",
        logo: "/imgs/fifa/bor.png",
        games: 48,
        wins: 20,
        draws: 9,
        losses: 19,
        goalsScored: 126,
        goalsConceded: 117,
        goalDifference: 9,
        points: 69,
        color: "#4fcb90", // Yellow
      },
      {
        team: "Roma",
        logo: "/imgs/fifa/rom.png",
        games: 44,
        wins: 19,
        draws: 8,
        losses: 17,
        goalsScored: 95,
        goalsConceded: 97,
        goalDifference: -2,
        points: 65,
        color: "#4fcb90", // Dark Orange
      },
      {
        team: "Chelsea",
        logo: "/imgs/fifa/che.png",
        games: 42,
        wins: 18,
        draws: 10,
        losses: 14,
        goalsScored: 101,
        goalsConceded: 82,
        goalDifference: 19,
        points: 64,
        color: "#4b98de", // Blue
      },
      {
        team: "Tottenham",
        logo: "/imgs/fifa/tot.png",
        games: 43,
        wins: 17,
        draws: 13,
        losses: 13,
        goalsScored: 107,
        goalsConceded: 80,
        goalDifference: 27,
        points: 64,
        color: "#4b98de", // Navy Blue
      },
      {
        team: "Arsenal",
        logo: "/imgs/fifa/ars.png",
        games: 39,
        wins: 18,
        draws: 8,
        losses: 13,
        goalsScored: 97,
        goalsConceded: 75,
        goalDifference: 22,
        points: 62,
        color: "#ea7878", // Red
      },
      {
        team: "Manchester City",
        logo: "/imgs/fifa/mci.png",
        games: 39,
        wins: 16,
        draws: 13,
        losses: 10,
        goalsScored: 94,
        goalsConceded: 78,
        goalDifference: 16,
        points: 61,
        color: "#ea7878", // Blue
      },
      {
        team: "Milan",
        logo: "/imgs/fifa/mil.png",
        games: 39,
        wins: 16,
        draws: 13,
        losses: 10,
        goalsScored: 95,
        goalsConceded: 89,
        goalDifference: 6,
        points: 61,
        color: "#ea7878", // Red
      },
      {
        team: "Inter",
        logo: "/imgs/fifa/int.png",
        games: 44,
        wins: 18,
        draws: 6,
        losses: 20,
        goalsScored: 92,
        goalsConceded: 99,
        goalDifference: -7,
        points: 60,
        color: "#4fcb90", // Blue
      },
      {
        team: "Lazio",
        logo: "/imgs/fifa/laz.png",
        games: 39,
        wins: 17,
        draws: 8,
        losses: 14,
        goalsScored: 99,
        goalsConceded: 90,
        goalDifference: 9,
        points: 59,
        color: "#ea7878", // Blue
      },
      {
        team: "Zenit",
        logo: "/imgs/fifa/zen.png",
        games: 39,
        wins: 17,
        draws: 8,
        losses: 14,
        goalsScored: 104,
        goalsConceded: 101,
        goalDifference: 3,
        points: 59,
        color: "#ea7878", // Blue
      },
      {
        team: "Spartak Moscow",
        logo: "/imgs/fifa/spa.png",
        games: 39,
        wins: 15,
        draws: 11,
        losses: 13,
        goalsScored: 84,
        goalsConceded: 87,
        goalDifference: -3,
        points: 56,
        color: "#ea7878", // Red
      },
      {
        team: "Liverpool",
        logo: "/imgs/fifa/liv.png",
        games: 40,
        wins: 16,
        draws: 8,
        losses: 16,
        goalsScored: 90,
        goalsConceded: 89,
        goalDifference: 1,
        points: 56,
        color: "#ea7878", // Dark Red
      },
      {
        team: "Stoke City",
        logo: "/imgs/fifa/sto.png",
        games: 43,
        wins: 13,
        draws: 17,
        losses: 13,
        goalsScored: 97,
        goalsConceded: 107,
        goalDifference: -10,
        points: 56,
        color: "#4fcb90", // Red
      },
      {
        team: "Benfica",
        logo: "/imgs/fifa/ben.png",
        games: 40,
        wins: 14,
        draws: 13,
        losses: 13,
        goalsScored: 92,
        goalsConceded: 87,
        goalDifference: 5,
        points: 55,
        color: "#ea7878", // Orange
      },
      {
        team: "Napoli",
        logo: "/imgs/fifa/nap.png",
        games: 40,
        wins: 14,
        draws: 13,
        losses: 13,
        goalsScored: 87,
        goalsConceded: 97,
        goalDifference: -10,
        points: 55,
        color: "#ea7878", // Blue
      },
      {
        team: "Borussia Monhengladbah",
        logo: "/imgs/fifa/bmo.png",
        games: 40,
        wins: 16,
        draws: 5,
        losses: 19,
        goalsScored: 84,
        goalsConceded: 98,
        goalDifference: -14,
        points: 53,
        color: "#ea7878", // Green
      },
      {
        team: "Valencia",
        logo: "/imgs/fifa/val.png",
        games: 41,
        wins: 15,
        draws: 8,
        losses: 18,
        goalsScored: 95,
        goalsConceded: 98,
        goalDifference: -3,
        points: 53,
        color: "#4b98de", // Orange
      },
      {
        team: "Leicester City",
        logo: "/imgs/fifa/lei.png",
        games: 43,
        wins: 14,
        draws: 11,
        losses: 18,
        goalsScored: 101,
        goalsConceded: 113,
        goalDifference: -12,
        points: 53,
        color: "#4b98de", // Blue
      },
      {
        team: "Atletico Madrid",
        logo: "/imgs/fifa/atm.png",
        games: 42,
        wins: 14,
        draws: 10,
        losses: 18,
        goalsScored: 91,
        goalsConceded: 88,
        goalDifference: 3,
        points: 52,
        color: "#4b98de", // Red
      },
      {
        team: "Bayer Leverkusen",
        logo: "/imgs/fifa/lev.png",
        games: 44,
        wins: 13,
        draws: 12,
        losses: 19,
        goalsScored: 108,
        goalsConceded: 125,
        goalDifference: -17,
        points: 51,
        color: "#4fcb90", // Red
      },
      {
        team: "Olympique Lyon",
        logo: "/imgs/fifa/lyo.png",
        games: 41,
        wins: 14,
        draws: 8,
        losses: 19,
        goalsScored: 92,
        goalsConceded: 97,
        goalDifference: -5,
        points: 50,
        color: "#4b98de", // Blue
      },
      {
        team: "Ajax",
        logo: "/imgs/fifa/aja.png",
        games: 40,
        wins: 12,
        draws: 10,
        losses: 18,
        goalsScored: 74,
        goalsConceded: 105,
        goalDifference: -31,
        points: 46,
        color: "#ea7878", // Red
      },
      {
        team: "Crystal Palace",
        logo: "/imgs/fifa/cry.png",
        games: 40,
        wins: 12,
        draws: 9,
        losses: 19,
        goalsScored: 75,
        goalsConceded: 92,
        goalDifference: -17,
        points: 45,
        color: "#4fcb90", // Blue
      },
      {
        team: "PSV",
        logo: "/imgs/fifa/psv.png",
        games: 41,
        wins: 11,
        draws: 9,
        losses: 21,
        goalsScored: 71,
        goalsConceded: 93,
        goalDifference: -22,
        points: 42,
        color: "#4b98de", // Red
      },
      {
        team: "Atlectic Bilbao",
        logo: "/imgs/fifa/atb.png",
        games: 40,
        wins: 11,
        draws: 8,
        losses: 21,
        goalsScored: 74,
        goalsConceded: 111,
        goalDifference: -37,
        points: 41,
        color: "#4fcb90", // Red
      },
      {
        team: "PSG",
        logo: "/imgs/fifa/psg.png",
        games: 40,
        wins: 10,
        draws: 11,
        losses: 19,
        goalsScored: 87,
        goalsConceded: 102,
        goalDifference: -15,
        points: 41,
        color: "#4b98de", // Blue
      },
      {
        team: "OGC Nice",
        logo: "/imgs/fifa/nic.png",
        games: 40,
        wins: 10,
        draws: 5,
        losses: 25,
        goalsScored: 74,
        goalsConceded: 115,
        goalDifference: -41,
        points: 35,
        color: "#4b98de", // Red
      },
      {
        team: "Marseille",
        logo: "/imgs/fifa/mar.png",
        games: 40,
        wins: 7,
        draws: 12,
        losses: 21,
        goalsScored: 62,
        goalsConceded: 89,
        goalDifference: -27,
        points: 33,
        color: "#4b98de", // Blue
      },
      {
        team: "Sevillia",
        logo: "/imgs/fifa/sev.png",
        games: 39,
        wins: 6,
        draws: 13,
        losses: 20,
        goalsScored: 74,
        goalsConceded: 107,
        goalDifference: -33,
        points: 31,
        color: "#4fcb90", // Red
      },
    ],
  },
  "2016/17": {
    standings: [
      {
        team: "Bayern Munich",
        logo: "/imgs/fifa/bay.png",
        games: 40,
        wins: 26,
        draws: 4,
        losses: 10,
        goalsScored: 100,
        goalsConceded: 61,
        goalDifference: 39,
        points: 82,
        color: "#ea7878", // Red
      },
      {
        team: "Barcelona",
        logo: "/imgs/fifa/bar.png",
        games: 40,
        wins: 23,
        draws: 7,
        losses: 10,
        goalsScored: 104,
        goalsConceded: 67,
        goalDifference: 37,
        points: 76,
        color: "#4b98de", // Purple
      },
      {
        team: "Borussia Dortmund",
        logo: "/imgs/fifa/bor.png",
        games: 40,
        wins: 23,
        draws: 6,
        losses: 11,
        goalsScored: 102,
        goalsConceded: 73,
        goalDifference: 29,
        points: 75,
        color: "#4fcb90", // Yellow
      },
      {
        team: "Real Madrid",
        logo: "/imgs/fifa/rm.png",
        games: 40,
        wins: 22,
        draws: 8,
        losses: 10,
        goalsScored: 121,
        goalsConceded: 92,
        goalDifference: 29,
        points: 74,
        color: "#4fcb90", // Navy Blue
      },
      {
        team: "Chelsea",
        logo: "/imgs/fifa/che.png",
        games: 40,
        wins: 19,
        draws: 14,
        losses: 7,
        goalsScored: 105,
        goalsConceded: 67,
        goalDifference: 38,
        points: 71,
        color: "#4b98de", // Blue
      },
      {
        team: "Arsenal",
        logo: "/imgs/fifa/ars.png",
        games: 40,
        wins: 19,
        draws: 8,
        losses: 13,
        goalsScored: 106,
        goalsConceded: 83,
        goalDifference: 23,
        points: 65,
        color: "#ea7878", // Red
      },
      {
        team: "Lazio",
        logo: "/imgs/fifa/laz.png",
        games: 40,
        wins: 19,
        draws: 8,
        losses: 13,
        goalsScored: 88,
        goalsConceded: 93,
        goalDifference: -5,
        points: 65,
        color: "#ea7878", // Blue
      },
      {
        team: "Manchester United",
        logo: "/imgs/fifa/mu.png",
        games: 40,
        wins: 17,
        draws: 13,
        losses: 10,
        goalsScored: 98,
        goalsConceded: 84,
        goalDifference: 14,
        points: 64,
        color: "#ea7878", // Dark Red
      },
      {
        team: "Milan",
        logo: "/imgs/fifa/mil.png",
        games: 40,
        wins: 18,
        draws: 6,
        losses: 16,
        goalsScored: 93,
        goalsConceded: 86,
        goalDifference: 7,
        points: 60,
        color: "#4b98de", // Red
      },
      {
        team: "Bayer Leverkusen",
        logo: "/imgs/fifa/lev.png",
        games: 40,
        wins: 18,
        draws: 6,
        losses: 16,
        goalsScored: 98,
        goalsConceded: 98,
        goalDifference: 0,
        points: 60,
        color: "#ea7878", // Red
      },
      {
        team: "Inter",
        logo: "/imgs/fifa/int.png",
        games: 40,
        wins: 16,
        draws: 12,
        losses: 12,
        goalsScored: 92,
        goalsConceded: 80,
        goalDifference: 12,
        points: 60,
        color: "#4fcb90", // Blue
      },
      {
        team: "Atletico Madrid",
        logo: "/imgs/fifa/atm.png",
        games: 40,
        wins: 16,
        draws: 11,
        losses: 13,
        goalsScored: 95,
        goalsConceded: 90,
        goalDifference: 5,
        points: 59,
        color: "#4fcb90", // Red
      },
      {
        team: "Tottenham",
        logo: "/imgs/fifa/tot.png",
        games: 40,
        wins: 16,
        draws: 8,
        losses: 16,
        goalsScored: 91,
        goalsConceded: 84,
        goalDifference: 7,
        points: 56,
        color: "#4b98de", // Navy Blue
      },
      {
        team: "Everton",
        logo: "/imgs/fifa/eve.png",
        games: 40,
        wins: 16,
        draws: 7,
        losses: 17,
        goalsScored: 88,
        goalsConceded: 102,
        goalDifference: -14,
        points: 55,
        color: "#4b98de", // Blue
      },
      {
        team: "Zenit",
        logo: "/imgs/fifa/zen.png",
        games: 40,
        wins: 16,
        draws: 7,
        losses: 17,
        goalsScored: 81,
        goalsConceded: 96,
        goalDifference: -15,
        points: 55,
        color: "#ea7878", // Blue
      },
      {
        team: "Benfica",
        logo: "/imgs/fifa/ben.png",
        games: 40,
        wins: 15,
        draws: 10,
        losses: 15,
        goalsScored: 92,
        goalsConceded: 89,
        goalDifference: 3,
        points: 55,
        color: "#4b98de", // Orange
      },
      {
        team: "Roma",
        logo: "/imgs/fifa/rom.png",
        games: 40,
        wins: 16,
        draws: 6,
        losses: 18,
        goalsScored: 94,
        goalsConceded: 96,
        goalDifference: -2,
        points: 54,
        color: "#4fcb90", // Dark Orange
      },
      {
        team: "Athletic Bilbao",
        logo: "/imgs/fifa/atb.png",
        games: 40,
        wins: 14,
        draws: 11,
        losses: 15,
        goalsScored: 94,
        goalsConceded: 84,
        goalDifference: 10,
        points: 53,
        color: "#4fcb90", // Red
      },
      {
        team: "Fenerbahçe",
        logo: "/imgs/fifa/fen.png",
        games: 40,
        wins: 15,
        draws: 5,
        losses: 20,
        goalsScored: 80,
        goalsConceded: 90,
        goalDifference: -10,
        points: 50,
        color: "#ea7878", // Orange
      },
      {
        team: "CSKA",
        logo: "/imgs/fifa/csk.png",
        games: 40,
        wins: 14,
        draws: 8,
        losses: 18,
        goalsScored: 93,
        goalsConceded: 103,
        goalDifference: -10,
        points: 50,
        color: "#4b98de", // Red
      },
      {
        team: "Juventus",
        logo: "/imgs/fifa/juv.png",
        games: 40,
        wins: 14,
        draws: 8,
        losses: 18,
        goalsScored: 57,
        goalsConceded: 95,
        goalDifference: -38,
        points: 50,
        color: "#4fcb90", // Navy Blue
      },
      {
        team: "Manchester City",
        logo: "/imgs/fifa/mci.png",
        games: 40,
        wins: 13,
        draws: 11,
        losses: 16,
        goalsScored: 83,
        goalsConceded: 77,
        goalDifference: 6,
        points: 50,
        color: "#4fcb90", // Blue
      },
      {
        team: "Porto",
        logo: "/imgs/fifa/por.png",
        games: 40,
        wins: 14,
        draws: 7,
        losses: 19,
        goalsScored: 78,
        goalsConceded: 90,
        goalDifference: -12,
        points: 49,
        color: "#4fcb90", // Blue
      },
      {
        team: "PSG",
        logo: "/imgs/fifa/psg.png",
        games: 40,
        wins: 14,
        draws: 6,
        losses: 20,
        goalsScored: 99,
        goalsConceded: 98,
        goalDifference: 1,
        points: 48,
        color: "#4b98de", // Blue
      },
      {
        team: "Napoli",
        logo: "/imgs/fifa/nap.png",
        games: 40,
        wins: 12,
        draws: 11,
        losses: 17,
        goalsScored: 93,
        goalsConceded: 93,
        goalDifference: 0,
        points: 47,
        color: "#4fcb90", // Blue
      },
      {
        team: "Valencia",
        logo: "/imgs/fifa/val.png",
        games: 40,
        wins: 13,
        draws: 6,
        losses: 21,
        goalsScored: 83,
        goalsConceded: 102,
        goalDifference: -19,
        points: 45,
        color: "#ea7878", // Orange
      },
      {
        team: "Galatasaray",
        logo: "/imgs/fifa/gal.png",
        games: 40,
        wins: 11,
        draws: 9,
        losses: 20,
        goalsScored: 86,
        goalsConceded: 113,
        goalDifference: -27,
        points: 42,
        color: "#4b98de", // Orange
      },
      {
        team: "Liverpool",
        logo: "/imgs/fifa/liv.png",
        games: 40,
        wins: 12,
        draws: 5,
        losses: 23,
        goalsScored: 82,
        goalsConceded: 103,
        goalDifference: -21,
        points: 41,
        color: "#ea7878", // Dark Red
      },
      {
        team: "Sevillia",
        logo: "/imgs/fifa/sev.png",
        games: 40,
        wins: 9,
        draws: 10,
        losses: 21,
        goalsScored: 63,
        goalsConceded: 105,
        goalDifference: -42,
        points: 37,
        color: "#ea7878", // Red
      },
      {
        team: "Shakhtar",
        logo: "/imgs/fifa/sha.png",
        games: 40,
        wins: 9,
        draws: 8,
        losses: 23,
        goalsScored: 71,
        goalsConceded: 116,
        goalDifference: -45,
        points: 35,
        color: "#4b98de", // Orange
      },
    ],
  },
  "2015/16": {
    standings: [
      {
        team: "PSG",
        logo: "/imgs/fifa/psg.png",
        games: 32,
        wins: 18,
        draws: 5,
        losses: 9,
        goalsScored: 88,
        goalsConceded: 70,
        goalDifference: 18,
        points: 59,
        color: "#4b98de", // Blue
      },
      {
        team: "Manchester City",
        logo: "/imgs/fifa/mci.png",
        games: 32,
        wins: 18,
        draws: 4,
        losses: 10,
        goalsScored: 94,
        goalsConceded: 81,
        goalDifference: 13,
        points: 58,
        color: "#4fcb90", // Blue
      },
      {
        team: "Liverpool",
        logo: "/imgs/fifa/liv.png",
        games: 32,
        wins: 16,
        draws: 8,
        losses: 8,
        goalsScored: 87,
        goalsConceded: 67,
        goalDifference: 20,
        points: 56,
        color: "#ea7878", // Dark Red
      },
      {
        team: "Juventus",
        logo: "/imgs/fifa/juv.png",
        games: 32,
        wins: 17,
        draws: 5,
        losses: 10,
        goalsScored: 79,
        goalsConceded: 68,
        goalDifference: 11,
        points: 56,
        color: "#4fcb90", // Navy Blue
      },
      {
        team: "Shakhtar",
        logo: "/imgs/fifa/sha.png",
        games: 32,
        wins: 14,
        draws: 11,
        losses: 7,
        goalsScored: 85,
        goalsConceded: 81,
        goalDifference: 4,
        points: 53,
        color: "#4b98de", // Orange
      },
      {
        team: "Napoli",
        logo: "/imgs/fifa/nap.png",
        games: 32,
        wins: 16,
        draws: 5,
        losses: 11,
        goalsScored: 66,
        goalsConceded: 61,
        goalDifference: 5,
        points: 53,
        color: "#4fcb90", // Blue
      },
      {
        team: "Inter",
        logo: "/imgs/fifa/int.png",
        games: 32,
        wins: 15,
        draws: 7,
        losses: 10,
        goalsScored: 74,
        goalsConceded: 54,
        goalDifference: 20,
        points: 52,
        color: "#4b98de", // Blue
      },
      {
        team: "Bayern Munich",
        logo: "/imgs/fifa/bay.png",
        games: 32,
        wins: 15,
        draws: 7,
        losses: 10,
        goalsScored: 57,
        goalsConceded: 37,
        goalDifference: 20,
        points: 52,
        color: "#4b98de", // Red
      },
      {
        team: "Atletico Madrid",
        logo: "/imgs/fifa/atm.png",
        games: 32,
        wins: 16,
        draws: 4,
        losses: 12,
        goalsScored: 76,
        goalsConceded: 72,
        goalDifference: 4,
        points: 52,
        color: "#4fcb90", // Red
      },
      {
        team: "Everton",
        logo: "/imgs/fifa/eve.png",
        games: 32,
        wins: 14,
        draws: 9,
        losses: 9,
        goalsScored: 68,
        goalsConceded: 69,
        goalDifference: -1,
        points: 51,
        color: "#4fcb90", // Blue
      },
      {
        team: "Porto",
        logo: "/imgs/fifa/por.png",
        games: 32,
        wins: 12,
        draws: 9,
        losses: 11,
        goalsScored: 82,
        goalsConceded: 77,
        goalDifference: 5,
        points: 45,
        color: "#4fcb90", // Blue
      },
      {
        team: "Borussia Dortmund",
        logo: "/imgs/fifa/bor.png",
        games: 32,
        wins: 11,
        draws: 11,
        losses: 10,
        goalsScored: 75,
        goalsConceded: 61,
        goalDifference: 14,
        points: 44,
        color: "#4b98de", // Yellow
      },
      {
        team: "Roma",
        logo: "/imgs/fifa/rom.png",
        games: 32,
        wins: 10,
        draws: 11,
        losses: 11,
        goalsScored: 65,
        goalsConceded: 64,
        goalDifference: 1,
        points: 41,
        color: "#ea7878", // Dark Orange
      },
      {
        team: "Barcelona",
        logo: "/imgs/fifa/bar.png",
        games: 32,
        wins: 11,
        draws: 8,
        losses: 13,
        goalsScored: 91,
        goalsConceded: 101,
        goalDifference: -10,
        points: 41,
        color: "#4fcb90", // Purple
      },
      {
        team: "Manchester United",
        logo: "/imgs/fifa/mu.png",
        games: 32,
        wins: 10,
        draws: 9,
        losses: 13,
        goalsScored: 80,
        goalsConceded: 73,
        goalDifference: 7,
        points: 39,
        color: "#ea7878", // Dark Red
      },
      {
        team: "CSKA",
        logo: "/imgs/fifa/csk.png",
        games: 32,
        wins: 9,
        draws: 12,
        losses: 11,
        goalsScored: 66,
        goalsConceded: 73,
        goalDifference: -7,
        points: 39,
        color: "#4b98de", // Red
      },
      {
        team: "Valencia",
        logo: "/imgs/fifa/val.png",
        games: 32,
        wins: 12,
        draws: 3,
        losses: 17,
        goalsScored: 63,
        goalsConceded: 73,
        goalDifference: -10,
        points: 39,
        color: "#ea7878", // Orange
      },
      {
        team: "Real Madrid",
        logo: "/imgs/fifa/rm.png",
        games: 32,
        wins: 9,
        draws: 11,
        losses: 12,
        goalsScored: 79,
        goalsConceded: 81,
        goalDifference: -2,
        points: 38,
        color: "#ea7878", // Navy Blue
      },
      {
        team: "Arsenal",
        logo: "/imgs/fifa/ars.png",
        games: 32,
        wins: 10,
        draws: 8,
        losses: 14,
        goalsScored: 70,
        goalsConceded: 77,
        goalDifference: -7,
        points: 38,
        color: "#ea7878", // Red
      },
      {
        team: "Wolfsburg",
        logo: "/imgs/fifa/wfs.png",
        games: 32,
        wins: 8,
        draws: 12,
        losses: 12,
        goalsScored: 53,
        goalsConceded: 61,
        goalDifference: -8,
        points: 36,
        color: "#4b98de", // Green
      },
      {
        team: "Milan",
        logo: "/imgs/fifa/mil.png",
        games: 32,
        wins: 9,
        draws: 9,
        losses: 14,
        goalsScored: 67,
        goalsConceded: 90,
        goalDifference: -23,
        points: 36,
        color: "#ea7878", // Red
      },
      {
        team: "Zenit",
        logo: "/imgs/fifa/zen.png",
        games: 32,
        wins: 9,
        draws: 7,
        losses: 16,
        goalsScored: 62,
        goalsConceded: 83,
        goalDifference: -21,
        points: 34,
        color: "#ea7878", // Blue
      },
      {
        team: "Chelsea",
        logo: "/imgs/fifa/che.png",
        games: 32,
        wins: 9,
        draws: 6,
        losses: 17,
        goalsScored: 57,
        goalsConceded: 69,
        goalDifference: -12,
        points: 33,
        color: "#4b98de", // Blue
      },
      {
        team: "Schalke 04",
        logo: "/imgs/fifa/sch.png",
        games: 32,
        wins: 3,
        draws: 9,
        losses: 20,
        goalsScored: 44,
        goalsConceded: 85,
        goalDifference: -41,
        points: 18,
        color: "#ea7878", // Blue
      },
    ],
  },
}

// Helper function to get team color (as fallback)
const getTeamColor = (team: string) => {
  const teamColors = {
    red: [
      "Liverpool",
      "Bayern Munich",
      "Inter",
      "Bayer Leverkusen",
      "Newcastle",
      "AS Roma",
      "Galatasaray",
      "Sporting CP",
      "SS Lazio",
      "AS Monaco",
    ],
    blue: [
      "Chelsea",
      "Manchester City",
      "Barcelona",
      "Tottenham",
      "Milan",
      "Aston Villa",
      "Athletic Bilbao",
      "Manchester United",
      "Benfica",
      "Olympique Lyonnais",
    ],
    green: [
      "Juventus",
      "Real Madrid",
      "Arsenal",
      "Borussia Dortmund",
      "PSG",
      "Atletico Madrid",
      "Napoli",
      "RB Leipzig",
      "Fenerbahçe",
      "Al Hilal",
    ],
  }

  if (teamColors.red.includes(team)) return "#ea7878"
  if (teamColors.blue.includes(team)) return "#4b98de"
  if (teamColors.green.includes(team)) return "#4fcb90"
  return "transparent"
}

type FifaSeasonTabsProps = {
  currentSeasonData: any[]
  currentSeasonHighlights: any[]
  columns: any[]
}

export default function FifaSeasonTabs({ currentSeasonData, currentSeasonHighlights, columns }: FifaSeasonTabsProps) {
  const [activeSeason, setActiveSeason] = useState(seasons[0])

  // Process past season data for display
  const getPastSeasonTableData = (season: string) => {
    if (!pastSeasonsData[season as keyof typeof pastSeasonsData]) {
      return []
    }

    return pastSeasonsData[season as keyof typeof pastSeasonsData].standings.map((entry, index) => ({
      position: index + 1,
      team: (
        <div className="flex items-center space-x-2">
          <Image
            src={entry.logo || "/imgs/fifa/new.png"}
            alt={entry.team}
            width={24}
            height={24}
            className="rounded-full"
          />
          <span className="relative">
            {entry.team}
            <span
              className="absolute bottom-0 left-0 w-[0.85em] h-[2px]"
              style={{ backgroundColor: entry.color || getTeamColor(entry.team) }}
            />
          </span>
        </div>
      ),
      games: entry.games,
      wins: entry.wins,
      draws: entry.draws,
      losses: entry.losses,
      goalsScored: entry.goalsScored,
      goalsConceded: entry.goalsConceded,
      goalDifference: entry.goalDifference,
      points: entry.points,
      hoverColor: entry.color || getTeamColor(entry.team),
      className: index === 0 ? "bg-amber-50" : undefined, 
    }))
  }

  // Render content based on active tab
  const renderContent = () => {
    if (activeSeason === "2024/25") {
      return (
        <>
          <div className="fifa-standings-table">
            <DataTable columns={columns} data={currentSeasonData} />
          </div>

          <section className="mt-12">
            <h2 className="text-title font-bold mb-6">Highlights</h2>
            <div className="px-12">
              <VideoCarousel videos={currentSeasonHighlights} />
            </div>
          </section>
        </>
      )
    } else {
      const pastSeasonData = getPastSeasonTableData(activeSeason)
      const pastSeasonHighlights = pastSeasonsData[activeSeason as keyof typeof pastSeasonsData]?.highlights || []
      // Use optional chaining to safely access the description property
      const seasonData = pastSeasonsData[activeSeason as keyof typeof pastSeasonsData]
      const seasonDescription = seasonData && "description" in seasonData ? seasonData.description : undefined

      return (
        <>
          {seasonDescription && <p className="text-basic text-gray-600 mb-8">{seasonDescription}</p>}

          <div className="fifa-standings-table">
            {pastSeasonData.length > 0 ? (
              <DataTable columns={columns} data={pastSeasonData} />
            ) : (
              <p className="text-gray-500 italic py-4">No data available for {activeSeason} season.</p>
            )}
          </div>

          <section className="mt-12">
            <h2 className="text-title font-bold mb-6">Highlights</h2>
            <div className="px-12">
              {pastSeasonHighlights.length > 0 ? (
                <VideoCarousel videos={pastSeasonHighlights} />
              ) : (
                <p className="text-gray-500 italic py-4">No highlights available for {activeSeason} season.</p>
              )}
            </div>
          </section>
        </>
      )
    }
  }

  return (
    <>
      {/* Season tabs */}
      <div className="mb-6">
        <div className="border-b border-gray-200">
          <nav className="-mb-px flex space-x-8 overflow-x-auto">
            {seasons.map((season) => (
              <button
                key={season}
                onClick={() => setActiveSeason(season)}
                className={`py-2 px-1 border-b-2 font-medium text-sm whitespace-nowrap ${
                  activeSeason === season
                    ? "border-blue-500 text-blue-600"
                    : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300"
                }`}
              >
                {season}
              </button>
            ))}
          </nav>
        </div>
      </div>

      <h2 className="text-title font-bold mb-6">Standings</h2>

      {/* Render content based on active tab */}
      {renderContent()}
    </>
  )
}
